import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {randomBytes} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const base=process.env.AGENTOA_URL || 'http://localhost:18081';
const secrets=fileURLToPath(new URL('../deploy/secrets/',import.meta.url));
const client='e5cd7e4891bf95d1d19206ce24a7b32e';
let token='';
let checks=0;
async function call(path,{method='GET',body,auth=token,status=200,extraHeaders}={}) {
  const headers={clientid:client};
  if(auth) headers.Authorization=`Bearer ${auth}`;
  if(body && !(body instanceof FormData)) headers['Content-Type']='application/json';
  if(extraHeaders) Object.assign(headers,extraHeaders);
  const res=await fetch(base+path,{method,headers,body:body instanceof FormData?body:body?JSON.stringify(body):undefined});
  const text=await res.text();
  assert.equal(res.status,status,`${method} ${path}: HTTP ${res.status}, ${text.slice(0,250)}`);
  checks++;
  if(!text) return {};
  try { return JSON.parse(text); } catch { return text; }
}
async function login(username,password) {
  const res=await call('/api/v1/auth/login',{method:'POST',body:{username,password},auth:''});
  assert.equal(res.code,200,res.msg);
  assert.equal(res.data.tokenType,'Bearer');
  assert.equal(res.data.accessToken.includes('.'),false,'Token must be opaque');
  assert.ok(res.requestId);
  return res.data;
}
await call('/actuator/health/readiness',{auth:''});
await call('/api/v1/auth/profile',{auth:'',status:401});
const captcha=await call('/auth/code',{auth:''});
assert.equal(captcha.data.captchaEnabled,false,'Use deploy/compose.smoke.yml for this local test');
const currentFile=secrets+'admin-current-password';
const usernameFile=secrets+'admin-current-username';
const adminUsername=existsSync(usernameFile)?readFileSync(usernameFile,'utf8').trim():'admin';
let password=readFileSync(existsSync(currentFile)?currentFile:secrets+'bootstrap-password','utf8').trim();
let session=await login(adminUsername,password); token=session.accessToken;
if(session.user.mustChangePassword) {
  await call('/api/v1/files',{status:403});
  const next=randomBytes(18).toString('hex');
  await call('/api/v1/auth/password',{method:'PUT',body:{oldPassword:password,newPassword:next}});
  writeFileSync(currentFile,next,{mode:0o600}); password=next;
  await call('/api/v1/auth/profile',{status:401});
  session=await login(adminUsername,password); token=session.accessToken;
}
const admin=token;
await call('/system/user/list');
assert.equal((await call('/system/tenant/list')).code,404); // Legacy API keeps its R response convention.
const form=new FormData(); form.append('file',new Blob(['AgentOA private storage smoke test'],{type:'text/plain'}),'foundation-smoke.txt');
const uploaded=await call('/api/v1/files',{method:'POST',body:form});
const fileId=uploaded.data.fileId;
assert.equal(typeof fileId,'string');
const bytes=await call(`/api/v1/files/${fileId}/download`);
assert.equal(bytes,'AgentOA private storage smoke test');
await call(`/api/v1/files/${fileId}/download`,{auth:'',status:401});
const invalid=new FormData(); invalid.append('file',new Blob(['<script>alert(1)</script>']),'bad.png');
await call('/api/v1/files',{method:'POST',body:invalid,status:400});
const probe=await call('/api/v1/foundation/probes',{method:'POST'});
await call(`/api/v1/foundation/probes/${probe.data.processInstanceId}/complete`,{method:'POST'});
await call(`/api/v1/foundation/probes/${probe.data.processInstanceId}/complete`,{method:'POST',status:404});
let message;
for(let n=0;n<12;n++) {
  const list=await call('/api/v1/messages'); message=list.data.records.find(x=>x.title==='基础底座验证');
  if(message) break; await new Promise(r=>setTimeout(r,1000));
}
assert.ok(message,'Outbox must persist a message');
await call(`/api/v1/messages/${message.id}/read`,{method:'PUT'});
const ticket=(await call('/api/v1/auth/ws-ticket',{method:'POST'})).data.ticket;
const wsUrl=base.replace(/^http/,'ws')+'/ws?ticket='+ticket;
await new Promise((resolve,reject)=>{
  const ws=new WebSocket(wsUrl); const timer=setTimeout(()=>{ws.close();reject(new Error('WS heartbeat timeout'));},8000);
  ws.onopen=()=>ws.send(JSON.stringify({type:'HEARTBEAT'}));
  ws.onmessage=e=>{assert.equal(JSON.parse(e.data).type,'HEARTBEAT');clearTimeout(timer);ws.close();resolve();};
  ws.onerror=()=>{clearTimeout(timer);reject(new Error('WS connection failed'));};
});
await new Promise((resolve,reject)=>{
  const ws=new WebSocket(wsUrl); const timer=setTimeout(()=>{ws.close();reject(new Error('Ticket replay did not fail'));},8000);
  ws.onopen=()=>{clearTimeout(timer);ws.close();reject(new Error('Ticket reused'));};
  ws.onerror=()=>{clearTimeout(timer);resolve();};
}); checks+=2;
const username='smoke_'+Date.now(); const tempPassword=randomBytes(12).toString('hex');
const role=await call('/system/role',{method:'POST',body:{roleName:username,roleKey:username,roleSort:9,dataScope:'5',status:'0',menuCheckStrictly:true,deptCheckStrictly:true,menuIds:[],deptIds:[]}});
assert.equal(role.code,200,role.msg);
const roleId=(await call('/system/role/list?roleName='+username)).rows[0].roleId;
const created=await call('/system/user',{method:'POST',body:{userName:username,nickName:'基础底座测试',password:tempPassword,deptId:103,status:'0',sex:'2',roleIds:[roleId],postIds:[1]}});
assert.equal(created.code,200,created.msg);
let other=await login(username,tempPassword); token=other.accessToken;
assert.equal(other.user.mustChangePassword,true);
const newPassword=randomBytes(12).toString('hex');
await call('/api/v1/auth/password',{method:'PUT',body:{oldPassword:tempPassword,newPassword}});
other=await login(username,newPassword); token=other.accessToken;
await call('/system/user/list',{status:403});
await call('/api/v1/hr/employees',{status:403}); // 角色矩阵：普通员工无花名册权限
await call(`/api/v1/files/${fileId}/download`,{status:404});
await call(`/api/v1/messages/${message.id}/read`,{method:'PUT',status:404});
await call('/api/v1/foundation/probes',{method:'POST',status:403});
const resetPassword=randomBytes(12).toString('hex');
const reset=await call('/system/user/resetPwd',{auth:admin,method:'PUT',body:{userId:other.user.userId,password:resetPassword}});
assert.equal(reset.code,200,reset.msg);
await call('/api/v1/auth/profile',{status:401});
other=await login(username,resetPassword); token=other.accessToken;
assert.equal(other.user.mustChangePassword,true,'Administrator reset must require another password change');
await call('/api/v1/files',{status:403});
await call('/api/v1/auth/password',{method:'PUT',body:{oldPassword:resetPassword,newPassword:randomBytes(12).toString('hex')}});
// Login again with a known replacement to test account disable separately.
const disablePassword=randomBytes(12).toString('hex');
await call('/system/user/resetPwd',{auth:admin,method:'PUT',body:{userId:other.user.userId,password:disablePassword}});
other=await login(username,disablePassword); token=other.accessToken;
await call('/system/user/changeStatus',{auth:admin,method:'PUT',body:{userId:other.user.userId,status:'1'}});
await call('/api/v1/auth/profile',{status:401});
token=admin;
await call(`/system/user/${other.user.userId}`,{method:'DELETE'});
await call(`/system/role/${roleId}`,{method:'DELETE'});
// ---- Module 1 (HR) contract smoke ----
const tree=await call('/api/v1/hr/departments/tree');
assert.ok(Array.isArray(tree.data),'部门树返回数组');
const postCode='SMOKE_'+Date.now();
const post=await call('/api/v1/hr/posts',{method:'POST',body:{positionCode:postCode,positionName:'冒烟岗位',positionSort:0,status:'0'}});
assert.equal(post.code,200,post.msg);
const postId=post.data.id;
const idemKey=randomBytes(16).toString('hex');
const onboardBody={name:'冒烟员工',gender:'2',deptId:'103',postId,entryDate:'2026-10-01'};
const on1=await call('/api/v1/hr/employees/onboard',{method:'POST',body:onboardBody,extraHeaders:{'Idempotency-Key':idemKey}});
assert.equal(on1.code,200,on1.msg);
assert.equal(on1.data.status,'PROBATION');
assert.ok(on1.data.employeeNo.startsWith('E'),'工号自动生成');
const on2=await call('/api/v1/hr/employees/onboard',{method:'POST',body:onboardBody,extraHeaders:{'Idempotency-Key':idemKey}});
assert.equal(on2.data.id,on1.data.id,'同键同请求必须返回首次结果');
const conflict=await call('/api/v1/hr/employees/onboard',{method:'POST',body:{...onboardBody,name:'冒烟员工二'},extraHeaders:{'Idempotency-Key':idemKey},status:409});
assert.equal(conflict.code,409);
const reg=await call('/api/v1/hr/employees/regularize',{method:'POST',body:{employeeId:on1.data.id},extraHeaders:{'Idempotency-Key':randomBytes(16).toString('hex')}});
assert.equal(reg.data.status,'ACTIVE');
const regAgain=await call('/api/v1/hr/employees/regularize',{method:'POST',body:{employeeId:on1.data.id},extraHeaders:{'Idempotency-Key':randomBytes(16).toString('hex')}});
assert.equal(regAgain.data.id,on1.data.id,'重复转正不产生第二个事件');
const changes=await call(`/api/v1/hr/employees/${on1.data.id}/changes`);
const eventTypes=changes.data.map(x=>x.eventType);
assert.ok(eventTypes.includes('ONBOARDING')&&eventTypes.includes('PROBATION'),'历史包含入职与转正');
assert.equal(eventTypes.filter(x=>x==='PROBATION').length,1,'转正事件只有一个');
const off=await call('/api/v1/hr/employees/offboard',{method:'POST',body:{employeeId:on1.data.id,reason:'冒烟离职',lastWorkingDay:'2026-12-31'},extraHeaders:{'Idempotency-Key':randomBytes(16).toString('hex')}});
assert.equal(off.data.status,'LEFT');
const offAgain=await call('/api/v1/hr/employees/offboard',{method:'POST',body:{employeeId:on1.data.id,reason:'冒烟离职'},extraHeaders:{'Idempotency-Key':randomBytes(16).toString('hex')}});
assert.equal(offAgain.data.id,on1.data.id,'重复离职只返回既有结果');
const leftList=await call('/api/v1/hr/employees?status=LEFT&pageNum=1&pageSize=100');
assert.ok(leftList.data.records.some(x=>x.id===on1.data.id),'离职状态可查询');
await call(`/api/v1/hr/posts/${postId}`,{method:'DELETE',status:409}); // 员工引用保护
await call(`/api/v1/hr/employees/${on1.data.id}`,{method:'DELETE',status:409}); // 非草稿不可删除
// ---- Module 2 (workflow) contract smoke ----
const wfDefs=await call('/api/v1/wf/definitions');
assert.equal(wfDefs.data.filter(d=>d.builtin).length,26,'Twenty-six built-in templates registered');
assert.ok(wfDefs.data.every(d=>d.status==='PUBLISHED'&&d.versions.length>0),'Templates published from structured chain config');
const wfCategories=await call('/api/v1/wf/categories');
assert.ok(['HR','FINANCE','ATTENDANCE','OTHER','ADMIN'].every(c=>wfCategories.data.some(x=>x.code===c)),'Five seeded flow categories (HR/Finance/Attendance/Other/Admin)');
async function makeUser(tag,roleIds) {
  const name='wf_'+tag+'_'+Date.now(); const temp=randomBytes(12).toString('hex');
  const created=await call('/system/user',{auth:admin,method:'POST',body:{userName:name,nickName:'WF '+tag,password:temp,deptId:103,status:'0',sex:'2',roleIds,postIds:[1]}});
  assert.equal(created.code,200,created.msg);
  const userId=(await call('/system/user/list?userName='+name,{auth:admin})).rows[0].userId;
  let s=await login(name,temp); token=s.accessToken;
  const pwd=randomBytes(12).toString('hex');
  await call('/api/v1/auth/password',{method:'PUT',body:{oldPassword:temp,newPassword:pwd}});
  s=await login(name,pwd); token=s.accessToken;
  return {token:s.accessToken,userId};
}
const wfLeader=await makeUser('mgr',[21]);
const wfEmp=await makeUser('emp',[22]);
const wfHr=await makeUser('hr',[20]);
const wfFin=await makeUser('fin',[23]);
const wfCash=await makeUser('cash',[24]);
const wfDir=await makeUser('dir',[25]);
token=admin;
const empRow=await call('/api/v1/hr/employees',{auth:admin,method:'POST',body:{name:'WF Applicant',gender:'2',deptId:'103',directLeaderId:String(wfLeader.userId),userId:String(wfEmp.userId),entryDate:'2026-09-01'},extraHeaders:{'Idempotency-Key':randomBytes(16).toString('hex')}});
assert.equal(empRow.code,200,empRow.msg);
const wfIdem=()=>randomBytes(16).toString('hex');
function idem(key){return {'Idempotency-Key':key};}
// leave: create + submit + idempotent replay + conflict
const quotaKey=wfIdem();
const quotaBefore=(await call('/api/v1/attendance/leaves/balance',{auth:wfEmp.token})).data.find(b=>b.leaveType==='annual');
const quota=await call('/api/v1/attendance/leaves/balance/grant',{auth:admin,method:'POST',body:{userId:String(wfEmp.userId),year:2026,leaveType:'annual',minutes:48000},extraHeaders:idem(quotaKey)});
assert.equal(quota.code,200,quota.msg);
assert.equal(quota.data.totalMinutes-quotaBefore.totalMinutes,48000,'Annual quota granted');
const quotaReplay=await call('/api/v1/attendance/leaves/balance/grant',{auth:admin,method:'POST',body:{userId:String(wfEmp.userId),year:2026,leaveType:'annual',minutes:48000},extraHeaders:idem(quotaKey)});
assert.equal(quotaReplay.data.totalMinutes,quota.data.totalMinutes,'Grant replay does not double-credit');
const leaveKey=wfIdem();
// 实例应钉在「提交时」的定义版本，后续定义变更不影响在途实例
const leaveDefVersion=(await call('/api/v1/wf/definitions')).data.find(d=>d.processKey==='leave').currentVersionNo;
const leaveBody={leaveType:'annual',startTime:'2026-10-12 09:00:00',endTime:'2026-10-12 18:00:00',reason:'WF smoke'};
const leave1=await call('/api/v1/attendance/leaves',{auth:wfEmp.token,method:'POST',body:leaveBody,extraHeaders:idem(leaveKey)});
assert.equal(leave1.code,200,leave1.msg);
assert.equal(leave1.data.formData.includes('durationMinutes'),true,'Duration computed by server');
const leaveId=leave1.data.id;
const leaveReplay=await call('/api/v1/attendance/leaves',{auth:wfEmp.token,method:'POST',body:leaveBody,extraHeaders:idem(leaveKey)});
assert.equal(leaveReplay.data.id,leaveId,'Same idempotency key replays first result');
const leaveConflict=await call('/api/v1/attendance/leaves',{auth:wfEmp.token,method:'POST',body:{...leaveBody,reason:'WF smoke 2'},extraHeaders:idem(leaveKey),status:409});
assert.equal(leaveConflict.code,409,'Same key different body conflicts');
const subKey=wfIdem();
const sub1=await call(`/api/v1/attendance/leaves/${leaveId}/submit`,{auth:wfEmp.token,method:'POST',body:{},extraHeaders:idem(subKey)});
assert.equal(sub1.code,200,sub1.msg);
const inst1=sub1.data.instanceId;
assert.equal(sub1.data.currentTasks[0].assigneeId,String(wfLeader.userId),'First node assigned to initiator leader');
const subReplay=await call(`/api/v1/attendance/leaves/${leaveId}/submit`,{auth:wfEmp.token,method:'POST',body:{},extraHeaders:idem(subKey)});
assert.equal(subReplay.data.instanceId,inst1,'Submit replay returns first result');
await call(`/api/v1/attendance/leaves/${leaveId}/submit`,{auth:wfEmp.token,method:'POST',body:{},extraHeaders:idem(wfIdem()),status:409});
// stranger visibility + authority
await call(`/api/v1/wf/instances/${inst1}`,{auth:wfFin.token,status:404});
await call(`/api/v1/wf/tasks/${sub1.data.currentTasks[0].taskId}/complete`,{auth:wfFin.token,method:'POST',body:{action:'agree'},extraHeaders:idem(wfIdem()),status:403});
// happy path: leader agree then HR agree
const leaderTask=sub1.data.currentTasks[0].taskId;
await call(`/api/v1/wf/tasks/${leaderTask}/complete`,{auth:wfLeader.token,method:'POST',body:{action:'agree',comment:'ok'},extraHeaders:idem(wfIdem())});
const hrTodo=await call('/api/v1/wf/tasks/todo',{auth:wfHr.token});
const hrTask=hrTodo.data.records.find(t=>String(t.instanceId)===String(inst1));
assert.ok(hrTask,'HR sees the filing task');
await call(`/api/v1/wf/tasks/${hrTask.taskId}/complete`,{auth:wfHr.token,method:'POST',body:{action:'agree',comment:'filed'},extraHeaders:idem(wfIdem())});
const detail1=await call(`/api/v1/wf/instances/${inst1}`,{auth:wfEmp.token});
assert.equal(detail1.data.status,2,'Approved after serial chain');
assert.equal(detail1.data.actions.length,2,'Two approve actions in history');
assert.equal(detail1.data.definitionVersionNo,leaveDefVersion,'Instance pinned to its definition version at submission');
await call(`/api/v1/wf/instances/${inst1}/history`,{auth:wfEmp.token});
await call(`/api/v1/wf/instances/${inst1}/diagram`,{auth:wfEmp.token});
const doneHr=await call('/api/v1/wf/tasks/done',{auth:wfHr.token});
assert.ok(doneHr.data.records.some(t=>String(t.instanceId)===String(inst1)),'Done list records handled task');
// reject path
const leave2=await call('/api/v1/attendance/leaves',{auth:wfEmp.token,method:'POST',body:{...leaveBody,startTime:'2026-10-13 09:00:00',endTime:'2026-10-13 18:00:00',reason:'WF reject'},extraHeaders:idem(wfIdem())});
const sub2=await call(`/api/v1/attendance/leaves/${leave2.data.id}/submit`,{auth:wfEmp.token,method:'POST',body:{},extraHeaders:idem(wfIdem())});
await call(`/api/v1/wf/tasks/${sub2.data.currentTasks[0].taskId}/complete`,{auth:wfLeader.token,method:'POST',body:{action:'reject',comment:'no'},extraHeaders:idem(wfIdem())});
const detail2=await call(`/api/v1/wf/instances/${sub2.data.instanceId}`,{auth:wfEmp.token});
assert.equal(detail2.data.status,3,'Rejected ends the instance');
assert.equal((await call(`/api/v1/attendance/leaves/${leave2.data.id}`,{auth:wfEmp.token})).data.status,4,'Rejected marks request');
// revoke path (initiator only, before any action)
const leave3=await call('/api/v1/attendance/leaves',{auth:wfEmp.token,method:'POST',body:{...leaveBody,startTime:'2026-10-14 09:00:00',endTime:'2026-10-14 18:00:00',reason:'WF revoke'},extraHeaders:idem(wfIdem())});
const sub3=await call(`/api/v1/attendance/leaves/${leave3.data.id}/submit`,{auth:wfEmp.token,method:'POST',body:{},extraHeaders:idem(wfIdem())});
const inst3=sub3.data.instanceId;
await call(`/api/v1/wf/instances/${inst3}/revoke`,{auth:wfLeader.token,method:'PUT',body:{},extraHeaders:idem(wfIdem()),status:403});
const revoked=await call(`/api/v1/wf/instances/${inst3}/revoke`,{auth:wfEmp.token,method:'PUT',body:{},extraHeaders:idem(wfIdem())});
assert.equal(revoked.data.status,4,'Revoked by initiator');
assert.equal((await call(`/api/v1/attendance/leaves/${leave3.data.id}`,{auth:wfEmp.token})).data.status,7,'Revoked marks request cancelled');
// revoke after an action conflicts
const leave4=await call('/api/v1/attendance/leaves',{auth:wfEmp.token,method:'POST',body:{...leaveBody,startTime:'2026-10-15 09:00:00',endTime:'2026-10-15 18:00:00',reason:'WF revoke2'},extraHeaders:idem(wfIdem())});
const sub4=await call(`/api/v1/attendance/leaves/${leave4.data.id}/submit`,{auth:wfEmp.token,method:'POST',body:{},extraHeaders:idem(wfIdem())});
await call(`/api/v1/wf/tasks/${sub4.data.currentTasks[0].taskId}/complete`,{auth:wfLeader.token,method:'POST',body:{action:'agree'},extraHeaders:idem(wfIdem())});
await call(`/api/v1/wf/instances/${sub4.data.instanceId}/revoke`,{auth:wfEmp.token,method:'PUT',body:{},extraHeaders:idem(wfIdem()),status:409});
// transfer path
const leave5=await call('/api/v1/attendance/leaves',{auth:wfEmp.token,method:'POST',body:{...leaveBody,startTime:'2026-10-16 09:00:00',endTime:'2026-10-16 18:00:00',reason:'WF transfer'},extraHeaders:idem(wfIdem())});
const sub5=await call(`/api/v1/attendance/leaves/${leave5.data.id}/submit`,{auth:wfEmp.token,method:'POST',body:{},extraHeaders:idem(wfIdem())});
const task5=sub5.data.currentTasks[0].taskId;
await call(`/api/v1/wf/tasks/${task5}/transfer`,{auth:wfLeader.token,method:'POST',body:{targetUserId:String(wfFin.userId),reason:'away'},extraHeaders:idem(wfIdem())});
await call(`/api/v1/wf/tasks/${task5}/complete`,{auth:wfFin.token,method:'POST',body:{action:'agree'},extraHeaders:idem(wfIdem())});
const detail5=await call(`/api/v1/wf/instances/${sub5.data.instanceId}`,{auth:wfEmp.token});
assert.ok(detail5.data.actions.some(a=>a.action==='transfer'&&a.newAssigneeName),'Transfer recorded with old/new assignee');
await call(`/api/v1/wf/tasks/${detail5.data.currentTasks[0].taskId}/complete`,{auth:wfHr.token,method:'POST',body:{action:'agree'},extraHeaders:idem(wfIdem())});
// reimburse branches by amount
async function reimburseChain(amount) {
  const draft=await call('/api/v1/finance/reimburses',{auth:wfEmp.token,method:'POST',body:{reimburseType:'expense',payMethod:'BANK_TRANSFER',details:[{expenseType:'office',occurDate:'2026-10-01',amount,description:'smoke'}]},extraHeaders:idem(wfIdem())});
  assert.equal(draft.code,200,draft.msg);
  const started=await call(`/api/v1/finance/reimburses/${draft.data.id}/submit`,{auth:wfEmp.token,method:'POST',body:{},extraHeaders:idem(wfIdem())});
  let task=started.data.currentTasks[0];
  const chain=[task.taskName];
  const actors={'主管审批':wfLeader.token,'财务审核':wfFin.token,'总监审批':wfDir.token,'出纳付款':wfCash.token};
  for(let n=0;n<6&&task;n++) {
    await call(`/api/v1/wf/tasks/${task.taskId}/complete`,{auth:actors[task.taskName],method:'POST',body:{action:'agree'},extraHeaders:idem(wfIdem())});
    const d=await call(`/api/v1/wf/instances/${started.data.instanceId}`,{auth:wfEmp.token});
    task=d.data.currentTasks[0];
    if(task) chain.push(task.taskName);
  }
  return chain;
}
assert.deepEqual(await reimburseChain('800.00'),['主管审批','财务审核'],'<=1000 chain skips cashier');
assert.deepEqual(await reimburseChain('8000.00'),['主管审批','财务审核','总监审批','出纳付款'],'>5000 chain includes director');
// lifecycle approvals drive the HR state machine
const regularTarget=await call('/api/v1/hr/employees/onboard',{auth:admin,method:'POST',body:{name:'WF Regular Target',gender:'2',deptId:'103',directLeaderId:String(wfLeader.userId),entryDate:'2026-09-01'},extraHeaders:idem(wfIdem())});
assert.equal(regularTarget.data.status,'PROBATION');
const life1=await call('/api/v1/hr/lifecycle-requests',{auth:wfEmp.token,method:'POST',body:{employeeId:regularTarget.data.id,requestType:'REGULARIZE',effectiveDate:'2026-10-01',formData:'{"probationReview":"ok"}'},extraHeaders:idem(wfIdem())});
assert.equal(life1.code,200,life1.msg);
const lifeSub1=await call(`/api/v1/hr/lifecycle-requests/${life1.data.id}/submit`,{auth:wfEmp.token,method:'POST',body:{},extraHeaders:idem(wfIdem())});
await call(`/api/v1/wf/tasks/${lifeSub1.data.currentTasks[0].taskId}/complete`,{auth:wfLeader.token,method:'POST',body:{action:'agree'},extraHeaders:idem(wfIdem())});
const lifeHrTodo=await call('/api/v1/wf/tasks/todo',{auth:wfHr.token});
const lifeTask=lifeHrTodo.data.records.find(t=>String(t.instanceId)===String(lifeSub1.data.instanceId));
await call(`/api/v1/wf/tasks/${lifeTask.taskId}/complete`,{auth:wfHr.token,method:'POST',body:{action:'agree'},extraHeaders:idem(wfIdem())});
assert.equal((await call(`/api/v1/hr/employees/${regularTarget.data.id}`,{auth:admin})).data.status,'ACTIVE','Regularize approval promotes employee');
const offTarget=await call('/api/v1/hr/employees/onboard',{auth:admin,method:'POST',body:{name:'WF Offboard Target',gender:'2',deptId:'103',directLeaderId:String(wfLeader.userId),entryDate:'2026-09-01'},extraHeaders:idem(wfIdem())});
const life2=await call('/api/v1/hr/lifecycle-requests',{auth:wfEmp.token,method:'POST',body:{employeeId:offTarget.data.id,requestType:'OFFBOARD',effectiveDate:'2026-10-01',formData:'{"leaveReason":"personal"}'},extraHeaders:idem(wfIdem())});
const lifeSub2=await call(`/api/v1/hr/lifecycle-requests/${life2.data.id}/submit`,{auth:wfEmp.token,method:'POST',body:{},extraHeaders:idem(wfIdem())});
await call(`/api/v1/wf/tasks/${lifeSub2.data.currentTasks[0].taskId}/complete`,{auth:wfLeader.token,method:'POST',body:{action:'agree'},extraHeaders:idem(wfIdem())});
const lifeHrTodo2=await call('/api/v1/wf/tasks/todo',{auth:wfHr.token});
const lifeTask2=lifeHrTodo2.data.records.find(t=>String(t.instanceId)===String(lifeSub2.data.instanceId));
await call(`/api/v1/wf/tasks/${lifeTask2.taskId}/complete`,{auth:wfHr.token,method:'POST',body:{action:'agree'},extraHeaders:idem(wfIdem())});
assert.equal((await call(`/api/v1/hr/employees/${offTarget.data.id}`,{auth:admin})).data.status,'LEFT','Offboard approval leaves employee');
// ---- Module 3 (attendance) contract smoke ----
const shiftCode='SMOKE_SHIFT_'+Date.now();
const shift=await call('/api/v1/attendance/shifts',{auth:admin,method:'POST',body:{shiftCode,shiftName:'Smoke 班次',workStartTime:'00:00:00',workEndTime:'23:59:00',restStartTime:'12:00:00',restEndTime:'12:30:00',isCrossDay:0,flexibleMinutes:0,graceMinutes:0,punchWindowStart:1440,punchWindowEnd:1440,status:'0'}});
assert.equal(shift.code,200,shift.msg);
const groupCode='SMOKE_GROUP_'+Date.now();
const group=await call('/api/v1/attendance/groups',{auth:admin,method:'POST',body:{groupCode,groupName:'Smoke 考勤组',shiftId:shift.data.id,workDays:'1,2,3,4,5,6,7',effectiveDate:'2026-01-01',status:'0'}});
assert.equal(group.code,200,group.msg);
const member=await call(`/api/v1/attendance/groups/${group.data.id}/members`,{auth:admin,method:'POST',body:{userId:String(wfEmp.userId),validFrom:'2026-01-01'}});
assert.equal(member.code,200,member.msg);
const shiftConflict=await call('/api/v1/attendance/shifts',{auth:admin,method:'POST',body:{shiftCode,shiftName:'重复编码',workStartTime:'09:00:00',workEndTime:'18:00:00',status:'0'},status:409});
assert.equal(shiftConflict.code,409,'Duplicate shift code rejected');
const punchKey=wfIdem();
const punchBody={punchType:1,device:'smoke-browser',address:'smoke address'};
const punch1=await call('/api/v1/attendance/punch',{auth:wfEmp.token,method:'POST',body:punchBody,extraHeaders:idem(punchKey)});
assert.equal(punch1.code,200,punch1.msg);
assert.ok(punch1.data.punchTime,'Server receive time returned');
const punchReplay=await call('/api/v1/attendance/punch',{auth:wfEmp.token,method:'POST',body:punchBody,extraHeaders:idem(punchKey)});
assert.equal(punchReplay.data.punchTime,punch1.data.punchTime,'Punch replay returns first result');
const punchOut=await call('/api/v1/attendance/punch',{auth:wfEmp.token,method:'POST',body:{...punchBody,punchType:2},extraHeaders:idem(wfIdem())});
assert.equal(punchOut.code,200,punchOut.msg);
const today=await call('/api/v1/attendance/punch/today',{auth:wfEmp.token});
assert.equal(today.data.todayPunched,true,'Today status exposes punch state');
assert.ok(today.data.punchInTime&&today.data.punchOutTime,'Punch in/out exposed');
const punchRecords=await call('/api/v1/attendance/punch/records',{auth:wfEmp.token});
assert.ok(punchRecords.data.records.length>=2,'Raw punch records retained');
const attLeaveBody={leaveType:'annual',startTime:'2026-11-03 09:00:00',endTime:'2026-11-03 18:00:00',reason:'Attendance smoke'};
const attLeave=await call('/api/v1/attendance/leaves',{auth:wfEmp.token,method:'POST',body:attLeaveBody,extraHeaders:idem(wfIdem())});
assert.equal(attLeave.code,200,attLeave.msg);
const attBefore=(await call('/api/v1/attendance/leaves/balance',{auth:wfEmp.token})).data.find(b=>b.leaveType==='annual');
const attSub=await call(`/api/v1/attendance/leaves/${attLeave.data.id}/submit`,{auth:wfEmp.token,method:'POST',body:{},extraHeaders:idem(wfIdem())});
assert.equal(attSub.code,200,attSub.msg);
const frozen=(await call('/api/v1/attendance/leaves/balance',{auth:wfEmp.token})).data.find(b=>b.leaveType==='annual');
assert.equal(frozen.frozenMinutes-attBefore.frozenMinutes,510,'Submit freezes the shift computed quota (540-30 rest)');
await call(`/api/v1/wf/tasks/${attSub.data.currentTasks[0].taskId}/complete`,{auth:wfLeader.token,method:'POST',body:{action:'agree'},extraHeaders:idem(wfIdem())});
const attHrTodo=await call('/api/v1/wf/tasks/todo',{auth:wfHr.token});
const attHrTask=attHrTodo.data.records.find(t=>String(t.instanceId)===String(attSub.data.instanceId));
assert.ok(attHrTask,'HR filing task created for attendance leave');
await call(`/api/v1/wf/tasks/${attHrTask.taskId}/complete`,{auth:wfHr.token,method:'POST',body:{action:'agree'},extraHeaders:idem(wfIdem())});
const settled=(await call('/api/v1/attendance/leaves/balance',{auth:wfEmp.token})).data.find(b=>b.leaveType==='annual');
assert.equal(settled.frozenMinutes,attBefore.frozenMinutes,'Approval settles frozen quota');
assert.equal(settled.usedMinutes-attBefore.usedMinutes,510,'Approval marks quota used');
const ledger=await call('/api/v1/attendance/leaves/ledger?leaveType=annual',{auth:wfEmp.token});
assert.ok(ledger.data.records.some(r=>r.action==='FREEZE')&&ledger.data.records.some(r=>r.action==='SETTLE'),'Ledger records freeze and settle');
await call(`/api/v1/attendance/leaves/ledger?userId=${wfLeader.userId}`,{auth:wfEmp.token,status:403});
const monthly=await call('/api/v1/attendance/statistics/monthly?yearMonth=2026-10',{auth:admin});
assert.equal(monthly.code,200,monthly.msg);
const daily=await call('/api/v1/attendance/statistics/daily?dateFrom=2026-10-01&dateTo=2026-10-31',{auth:admin});
assert.equal(daily.code,200,daily.msg);
const myDays=await call('/api/v1/attendance/days',{auth:wfEmp.token});
assert.equal(myDays.code,200,myDays.msg);
const cal=await call('/api/v1/attendance/calendar?year=2026',{auth:admin});
assert.equal(cal.code,200,cal.msg);
// ---- Module 4 (finance) contract smoke ----
const expenseTypes=await call('/api/v1/finance/expense-types',{auth:admin});
assert.equal(expenseTypes.code,200,expenseTypes.msg);
const etCode='SMOKE_ET_'+Date.now();
const expenseType=await call('/api/v1/finance/expense-types',{auth:wfFin.token,method:'POST',body:{name:'Smoke费用',code:etCode,sort:0,status:'0'}});
assert.equal(expenseType.code,200,expenseType.msg);
const etDup=await call('/api/v1/finance/expense-types',{auth:wfFin.token,method:'POST',body:{name:'重复编码',code:etCode,sort:0,status:'0'},status:409});
assert.equal(etDup.code,409,'Duplicate expense type code rejected');
await call('/api/v1/finance/expense-types',{auth:wfEmp.token,method:'POST',body:{name:'x',code:'NOPE_'+Date.now()},status:403});
const invBody={invoiceType:'VAT_NORMAL',invoiceCode:'',invoiceNo:'SMOKE-INV-'+Date.now(),invoiceDate:'2026-10-01',amount:'1000.00'};
const invoice=await call('/api/v1/finance/invoices',{auth:wfEmp.token,method:'POST',body:invBody});
assert.equal(invoice.code,200,invoice.msg);
assert.equal(invoice.data.occupationStatus,'FREE','New invoice is free');
const invDup=await call('/api/v1/finance/invoices',{auth:wfLeader.token,method:'POST',body:invBody,status:409});
assert.equal(invDup.code,409,'Duplicate invoice identity rejected');
await call(`/api/v1/finance/invoices/${invoice.data.id}`,{auth:wfLeader.token,status:403});
const invClaimBody={reimburseType:'expense',payMethod:'BANK_TRANSFER',totalAmount:'800.00',details:[{expenseType:'office',expenseTypeId:expenseType.data.id,occurDate:'2026-10-02',amount:'800.00',invoiceId:invoice.data.id,description:'smoke invoice claim'}]};
const invClaim=await call('/api/v1/finance/reimburses',{auth:wfEmp.token,method:'POST',body:invClaimBody,extraHeaders:idem(wfIdem())});
assert.equal(invClaim.code,200,invClaim.msg);
const invClaimSub=await call(`/api/v1/finance/reimburses/${invClaim.data.id}/submit`,{auth:wfEmp.token,method:'POST',body:{},extraHeaders:idem(wfIdem())});
assert.equal(invClaimSub.code,200,invClaimSub.msg);
const invOccupied=await call(`/api/v1/finance/invoices/${invoice.data.id}`,{auth:wfFin.token});
assert.equal(invOccupied.data.occupationStatus,'OCCUPIED','Submit occupies invoice');
assert.equal(String(invOccupied.data.occupiedReimburseId),String(invClaim.data.id),'Occupation bound to claim');
const reuseClaim=await call('/api/v1/finance/reimburses',{auth:wfEmp.token,method:'POST',body:{...invClaimBody,totalAmount:'100.00',details:[{expenseType:'office',occurDate:'2026-10-03',amount:'100.00',invoiceId:invoice.data.id}]},extraHeaders:idem(wfIdem())});
const reuseSub=await call(`/api/v1/finance/reimburses/${reuseClaim.data.id}/submit`,{auth:wfEmp.token,method:'POST',body:{},extraHeaders:idem(wfIdem()),status:409});
assert.equal(reuseSub.code,409,'Invoice cannot be occupied by two claims');
await call(`/api/v1/wf/tasks/${invClaimSub.data.currentTasks[0].taskId}/complete`,{auth:wfLeader.token,method:'POST',body:{action:'reject',comment:'smoke reject'},extraHeaders:idem(wfIdem())});
const invFreeAfterReject=await call(`/api/v1/finance/invoices/${invoice.data.id}`,{auth:wfFin.token});
assert.equal(invFreeAfterReject.data.occupationStatus,'FREE','Reject releases invoice');
const payClaim=await call('/api/v1/finance/reimburses',{auth:wfEmp.token,method:'POST',body:{reimburseType:'expense',payMethod:'BANK_TRANSFER',totalAmount:'800.00',details:[{expenseType:'office',occurDate:'2026-10-04',amount:'800.00',description:'smoke pay'}]},extraHeaders:idem(wfIdem())});
const payClaimSub=await call(`/api/v1/finance/reimburses/${payClaim.data.id}/submit`,{auth:wfEmp.token,method:'POST',body:{},extraHeaders:idem(wfIdem())});
let payTask=payClaimSub.data.currentTasks[0];
await call(`/api/v1/wf/tasks/${payTask.taskId}/complete`,{auth:wfLeader.token,method:'POST',body:{action:'agree'},extraHeaders:idem(wfIdem())});
const payDetail=await call(`/api/v1/wf/instances/${payClaimSub.data.instanceId}`,{auth:wfEmp.token});
payTask=payDetail.data.currentTasks[0];
await call(`/api/v1/wf/tasks/${payTask.taskId}/complete`,{auth:wfFin.token,method:'POST',body:{action:'agree'},extraHeaders:idem(wfIdem())});
const payReady=await call(`/api/v1/finance/reimburses/${payClaim.data.id}`,{auth:wfEmp.token});
assert.equal(payReady.data.status,5,'Approval moves claim to pending payment');
const payBody={amount:'800.00',payDate:'2026-10-15',paymentMethod:'BANK_TRANSFER',voucherNo:'SMOKE-V-1'};
const payMismatch=await call(`/api/v1/finance/reimburses/${payClaim.data.id}/pay`,{auth:wfCash.token,method:'POST',body:{...payBody,amount:'900.00'},extraHeaders:idem(wfIdem()),status:400});
assert.equal(payMismatch.code,400,'Pay amount must not exceed remaining payable (partial payments allowed)');
await call(`/api/v1/finance/reimburses/${payClaim.data.id}/pay`,{auth:wfEmp.token,method:'POST',body:payBody,extraHeaders:idem(wfIdem()),status:403});
await call(`/api/v1/finance/reimburses/${payClaim.data.id}/pay`,{auth:admin,method:'POST',body:payBody,extraHeaders:idem(wfIdem()),status:403});
const payKey=wfIdem();
const paid=await call(`/api/v1/finance/reimburses/${payClaim.data.id}/pay`,{auth:wfCash.token,method:'POST',body:payBody,extraHeaders:idem(payKey)});
assert.equal(paid.code,200,paid.msg);
assert.equal(paid.data.amount,'800.00','Payment amount recorded');
const payReplay=await call(`/api/v1/finance/reimburses/${payClaim.data.id}/pay`,{auth:wfCash.token,method:'POST',body:payBody,extraHeaders:idem(payKey)});
assert.equal(payReplay.data.id,paid.data.id,'Pay replay returns first result');
const payAgain=await call(`/api/v1/finance/reimburses/${payClaim.data.id}/pay`,{auth:wfCash.token,method:'POST',body:payBody,extraHeaders:idem(wfIdem()),status:409});
assert.equal(payAgain.code,409,'Second payment rejected');
const paidClaim=await call(`/api/v1/finance/reimburses/${payClaim.data.id}`,{auth:wfEmp.token});
assert.equal(paidClaim.data.status,6,'Payment marks claim paid');
const payments=await call('/api/v1/finance/payments',{auth:wfCash.token});
assert.equal(payments.code,200,payments.msg);
const pendingPay=await call('/api/v1/finance/reimburses/pending?status=5',{auth:wfCash.token});
assert.equal(pendingPay.code,200,pendingPay.msg);
const expenseReport=await call('/api/v1/finance/reports/expense',{auth:wfFin.token});
assert.equal(expenseReport.code,200,expenseReport.msg);
await call('/api/v1/finance/reports/expense',{auth:wfEmp.token,status:403});
// ---- Module 5 (notice) contract smoke ----
const noticeBody={title:'Smoke公告'+Date.now(),content:'公告内容 smoke',noticeType:'company',scopeType:'4',scopeValues:String(wfEmp.userId)};
const draft=await call('/api/v1/notice',{auth:wfHr.token,method:'POST',body:noticeBody});
assert.equal(draft.code,200,draft.msg);
assert.equal(draft.data.status,1,'Draft created');
await call('/api/v1/notice',{auth:wfEmp.token,method:'POST',body:noticeBody,status:403});
const empDraftList=await call('/api/v1/notice/list',{auth:wfEmp.token});
assert.ok(!empDraftList.data.records.some(x=>String(x.id)===String(draft.data.id)),'Draft hidden from non-audience');
await call(`/api/v1/notice/${draft.data.id}`,{auth:wfEmp.token,status:404});
const noticeTitle=noticeBody.title+' v2';
const updated=await call(`/api/v1/notice/${draft.data.id}`,{auth:wfHr.token,method:'PUT',body:{...noticeBody,title:noticeTitle}});
assert.equal(updated.code,200,updated.msg);
const pubKey=wfIdem();
const published=await call(`/api/v1/notice/${draft.data.id}/publish`,{auth:wfHr.token,method:'POST',body:{},extraHeaders:idem(pubKey)});
assert.equal(published.code,200,published.msg);
assert.equal(published.data.status,2,'Notice published');
assert.equal(published.data.audienceCount,1,'Audience snapshot size');
const pubReplay=await call(`/api/v1/notice/${draft.data.id}/publish`,{auth:wfHr.token,method:'POST',body:{},extraHeaders:idem(pubKey)});
assert.equal(pubReplay.data.id,published.data.id,'Publish replay returns first result');
const pubAgain=await call(`/api/v1/notice/${draft.data.id}/publish`,{auth:wfHr.token,method:'POST',body:{},extraHeaders:idem(wfIdem()),status:409});
assert.equal(pubAgain.code,409,'Second publish rejected');
await call(`/api/v1/notice/${draft.data.id}`,{auth:wfHr.token,method:'PUT',body:noticeBody,status:409});
let noticeMsg;
for(let n=0;n<90;n++) {
  const msgs=await call('/api/v1/messages?type=NOTICE',{auth:wfEmp.token});
  noticeMsg=msgs.data.records.find(m=>m.title===noticeTitle);
  if(noticeMsg) break; await new Promise(r=>setTimeout(r,1000));
}
assert.ok(noticeMsg,'Outbox delivers notice message');
const unread=await call('/api/v1/messages/unread-count',{auth:wfEmp.token});
assert.ok(unread.data.total>=1,'Unread count total');
assert.equal(typeof unread.data.notice,'number','Unread buckets expose notice count');
await call(`/api/v1/messages/${noticeMsg.id}/read`,{method:'PUT',auth:wfEmp.token});
await call('/api/v1/messages/read-all',{method:'PUT',auth:wfEmp.token});
await call(`/api/v1/notice/${draft.data.id}/read`,{method:'PUT',auth:wfEmp.token});
const readStatus=await call(`/api/v1/notice/${draft.data.id}/read-status`,{auth:wfHr.token});
assert.equal(readStatus.data.audienceCount,1,'Read status denominator is snapshot size');
assert.equal(readStatus.data.readCount,1,'Read recorded once');
await call(`/api/v1/notice/${draft.data.id}/revoke`,{method:'PUT',auth:wfHr.token});
await call(`/api/v1/notice/${draft.data.id}`,{auth:wfEmp.token,status:404});
const recalled=await call(`/api/v1/notice/${draft.data.id}`,{auth:wfHr.token});
assert.equal(recalled.data.status,3,'Recall keeps audit for manager');
const outboxFailed=await call('/api/v1/messages/outbox?eventStatus=FAILED',{auth:wfHr.token});
assert.equal(outboxFailed.code,200,outboxFailed.msg);
await call('/api/v1/messages/outbox?eventStatus=FAILED',{auth:wfEmp.token,status:403});
await call(`/api/v1/messages/${noticeMsg.id}`,{method:'DELETE',auth:wfEmp.token});

// ---- Module 5b (notice P1 NC-04: templates & scheduled push) contract smoke ----
const tplCode='smoke_tpl_'+Date.now();
const tpl=await call('/api/v1/notice/templates',{auth:wfHr.token,method:'POST',body:{templateCode:tplCode,name:'冒烟模板',titleTpl:'模板标题 {name}',contentTpl:'{name} 的模板消息',msgType:'NOTICE',vars:['name'],status:'1'}});
assert.equal(tpl.code,200,tpl.msg);
const tplBad=await call('/api/v1/notice/templates',{auth:wfHr.token,method:'POST',body:{templateCode:tplCode+'_bad',name:'x',titleTpl:'{ghost}',contentTpl:'c',msgType:'NOTICE',vars:['name'],status:'1'},status:400});
assert.equal(tplBad.code,400,'Undeclared placeholder rejected');
const tplMissing=await call(`/api/v1/notice/templates/${tplCode}/send`,{auth:wfHr.token,method:'POST',body:{scopeType:'4',scopeValues:String(wfEmp.userId),vars:{}},status:400});
assert.equal(tplMissing.code,400,'Missing template variable rejected');
await call('/api/v1/notice/templates/list',{auth:wfEmp.token,status:403});
await call('/api/v1/notice/push/list',{auth:wfEmp.token,status:403});
const sent=await call(`/api/v1/notice/templates/${tplCode}/send`,{auth:wfHr.token,method:'POST',body:{scopeType:'4',scopeValues:String(wfEmp.userId),vars:{name:'冒烟'}}});
assert.equal(sent.code,200,sent.msg);
assert.equal(sent.data,1,'Template send delivers to one receiver');
let tplMsg;
for(let n=0;n<90;n++) {
  const msgs=await call('/api/v1/messages?type=NOTICE&pageSize=100',{auth:wfEmp.token});
  tplMsg=(msgs.data.records||[]).find(m=>m.title==='模板标题 冒烟');
  if(tplMsg) break; await new Promise(r=>setTimeout(r,1000));
}
assert.ok(tplMsg,'Rendered template message delivered');
const pushBody={name:'Smoke定时推送 '+Date.now(),pushType:'2',templateId:String(tpl.data.id),scopeType:'4',scopeValues:String(wfEmp.userId),vars:{name:'定时'},scheduleType:'1',runAt:new Date(Date.now()+3000).toISOString().slice(0,19).replace('T',' '),status:'1'};
const push=await call('/api/v1/notice/push',{auth:wfHr.token,method:'POST',body:pushBody});
assert.equal(push.code,200,push.msg);
await call('/api/v1/notice/push',{auth:wfEmp.token,method:'POST',body:pushBody,status:403});
await call('/api/v1/notice/push/run',{auth:wfEmp.token,method:'POST',body:{},status:403});
let schedMsg;
for(let n=0;n<90;n++) {
  const msgs=await call('/api/v1/messages?type=NOTICE&pageSize=100',{auth:wfEmp.token});
  schedMsg=(msgs.data.records||[]).find(m=>m.title==='模板标题 定时');
  if(schedMsg) break; await new Promise(r=>setTimeout(r,1000));
}
assert.ok(schedMsg,'Scheduled push fires at run time');
const runs=await call(`/api/v1/notice/push/${push.data.id}/runs`,{auth:wfHr.token});
assert.equal(runs.data.records.length,1,'Execution history records one run');
assert.equal(runs.data.records[0].status,1,'Scheduled run succeeded');
const runScan=await call('/api/v1/notice/push/run',{auth:wfHr.token,method:'POST',body:{}});
assert.equal(runScan.data,0,'Rescan does not duplicate completed slot');
const runsAfter=await call(`/api/v1/notice/push/${push.data.id}/runs`,{auth:wfHr.token});
assert.equal(runsAfter.data.records.length,1,'No duplicate execution record');

// ---- Module 3b (attendance P1 AT-06: leave batches) contract smoke ----
const batchKey=wfIdem();
const batchGrant=await call('/api/v1/attendance/leaves/balance/grant',{auth:admin,method:'POST',body:{userId:String(wfEmp.userId),year:2026,leaveType:'compensatory',minutes:600,validFrom:'2026-10-01',expireDate:'2026-12-31'},extraHeaders:idem(batchKey)});
assert.equal(batchGrant.code,200,batchGrant.msg);
const batchReplay=await call('/api/v1/attendance/leaves/balance/grant',{auth:admin,method:'POST',body:{userId:String(wfEmp.userId),year:2026,leaveType:'compensatory',minutes:600,validFrom:'2026-10-01',expireDate:'2026-12-31'},extraHeaders:idem(batchKey)});
assert.equal(batchReplay.data.totalMinutes,batchGrant.data.totalMinutes,'Batch grant replay does not double-create');
const batches=await call(`/api/v1/attendance/leaves/batches?leaveType=compensatory&year=2026`,{auth:wfEmp.token});
assert.equal(batches.data.length,1,'Grant creates one batch');
assert.equal(batches.data[0].availableMinutes,600,'Batch remaining exposed');
await call(`/api/v1/attendance/leaves/batches?userId=${wfLeader.userId}`,{auth:wfEmp.token,status:403});
await call('/api/v1/attendance/leaves/expire-scan',{auth:wfEmp.token,method:'POST',body:{},status:403});
const expireScan=await call('/api/v1/attendance/leaves/expire-scan',{auth:admin,method:'POST',body:{}});
assert.equal(expireScan.code,200,expireScan.msg);
const expireScanAgain=await call('/api/v1/attendance/leaves/expire-scan',{auth:admin,method:'POST',body:{}});
assert.equal(expireScanAgain.data,0,'Rescan does not re-expire consumed batches');
// ---- Module 6 (knowledge) contract smoke ----
const kbSpaceBody={name:'KB Smoke '+Date.now(),spaceType:'3',description:'knowledge smoke'};
const kbSpace=await call('/api/v1/knowledge/spaces',{auth:wfHr.token,method:'POST',body:kbSpaceBody});
assert.equal(kbSpace.code,200,kbSpace.msg);
assert.equal(kbSpace.data.myRole,'OWNER','Space creator becomes OWNER');
await call('/api/v1/knowledge/spaces',{auth:wfFin.token,method:'POST',body:kbSpaceBody,status:403});
const kbEditor=await call(`/api/v1/knowledge/spaces/${kbSpace.data.id}/members`,{auth:wfHr.token,method:'POST',body:{userId:String(wfEmp.userId),role:'EDITOR'}});
assert.equal(kbEditor.code,200,kbEditor.msg);
assert.ok(kbEditor.data.grantedBy,'Membership records granter for audit');
const kbViewer=await call(`/api/v1/knowledge/spaces/${kbSpace.data.id}/members`,{auth:wfHr.token,method:'POST',body:{userId:String(wfFin.userId),role:'VIEWER'}});
assert.equal(kbViewer.code,200,kbViewer.msg);
const kbMembers=await call(`/api/v1/knowledge/spaces/${kbSpace.data.id}/members`,{auth:wfEmp.token});
assert.equal(kbMembers.data.length,3,'Owner plus two members');
const kbDocBody={spaceId:String(kbSpace.data.id),title:'KB Smoke Doc '+Date.now(),content:'# 项目管理\n项目管理是核心能力',tags:'smoke,kb'};
const kbDoc=await call('/api/v1/knowledge/documents',{auth:wfEmp.token,method:'POST',body:kbDocBody});
assert.equal(kbDoc.code,200,kbDoc.msg);
assert.equal(kbDoc.data.version,1,'New document starts at version 1');
await call('/api/v1/knowledge/documents',{auth:wfFin.token,method:'POST',body:kbDocBody,status:403});
const kbUpd=await call(`/api/v1/knowledge/documents/${kbDoc.data.id}`,{auth:wfEmp.token,method:'PUT',body:{...kbDocBody,baseVersion:1,changeSummary:'smoke update',content:'# 项目管理\n第二版正文'}});
assert.equal(kbUpd.code,200,kbUpd.msg);
assert.equal(kbUpd.data.version,2,'Commit bumps version');
const kbConflict=await call(`/api/v1/knowledge/documents/${kbDoc.data.id}`,{auth:wfEmp.token,method:'PUT',body:{...kbDocBody,baseVersion:1,content:'stale'},status:409});
assert.equal(kbConflict.code,409,'Stale baseVersion conflicts with 409');
const kbView=await call(`/api/v1/knowledge/documents/${kbDoc.data.id}`,{auth:wfFin.token});
assert.equal(kbView.data.myRole,'VIEWER','Viewer role resolved from membership');
const kbViewEdit=await call(`/api/v1/knowledge/documents/${kbDoc.data.id}`,{auth:wfFin.token,method:'PUT',body:{...kbDocBody,baseVersion:2},status:403});
assert.equal(kbViewEdit.code,403,'Viewer cannot edit');
await call(`/api/v1/knowledge/documents/${kbDoc.data.id}`,{auth:wfDir.token,status:404});
const kbVers=await call(`/api/v1/knowledge/documents/${kbDoc.data.id}/versions`,{auth:wfFin.token});
assert.equal(kbVers.data.length,2,'History keeps every committed version');
assert.ok(kbVers.data[1].content==null,'History list omits content');
const kbV1=await call(`/api/v1/knowledge/documents/${kbDoc.data.id}/versions/1`,{auth:wfFin.token});
assert.equal(kbV1.data.content,'# 项目管理\n项目管理是核心能力','Version snapshots are immutable');
const kbRollback=await call(`/api/v1/knowledge/documents/${kbDoc.data.id}/rollback/1`,{auth:wfEmp.token,method:'PUT'});
assert.equal(kbRollback.data.version,3,'Rollback appends a new version');
await call(`/api/v1/knowledge/documents/${kbDoc.data.id}/draft`,{auth:wfEmp.token,method:'PUT',body:{title:'草稿',content:'自动保存内容',baseVersion:3}});
const kbDraft=await call(`/api/v1/knowledge/documents/${kbDoc.data.id}/draft`,{auth:wfEmp.token});
assert.equal(kbDraft.data.baseVersion,3,'Draft records baseVersion');
const kbSearch=await call('/api/v1/knowledge/documents/search?keyword='+encodeURIComponent('项目管理'),{auth:wfEmp.token});
assert.ok(kbSearch.data.records.some(x=>String(x.documentId)===String(kbDoc.data.id)),'Search returns authorized hit');
assert.ok(kbSearch.data.records[0].highlight.includes('em'),'Search highlight marks keyword');
const kbSearchOut=await call('/api/v1/knowledge/documents/search?keyword='+encodeURIComponent('项目管理'),{auth:wfDir.token});
assert.equal(kbSearchOut.data.records.length,0,'Search filters by authorization');
const kbFileForm=new FormData();
kbFileForm.append('file',new Blob(['AgentOA knowledge cabinet smoke'],{type:'text/plain'}),'kb-smoke.txt');
kbFileForm.append('spaceId',String(kbSpace.data.id));
const kbFile=await call('/api/v1/knowledge/files',{auth:wfEmp.token,method:'POST',body:kbFileForm});
assert.equal(kbFile.code,200,kbFile.msg);
assert.equal(kbFile.data.fileName,'kb-smoke.txt','Upload binds business record');
await call('/api/v1/knowledge/files',{auth:wfFin.token,method:'POST',body:kbFileForm,status:403});
const kbBytes=await call(`/api/v1/knowledge/files/${kbFile.data.id}/download`,{auth:wfFin.token});
assert.equal(kbBytes,'AgentOA knowledge cabinet smoke','Viewer can download');
await call(`/api/v1/knowledge/files/${kbFile.data.id}/download`,{auth:wfDir.token,status:404});
const kbAfterDl=await call(`/api/v1/knowledge/files?spaceId=${kbSpace.data.id}`,{auth:wfEmp.token});
assert.ok(kbAfterDl.data.records[0].downloadCount>=1,'Download audit counter updated');
const kbDelFile=await call(`/api/v1/knowledge/files/${kbFile.data.id}`,{auth:wfEmp.token,method:'DELETE'});
assert.equal(kbDelFile.code,200,kbDelFile.msg);
const kbTrashFiles=await call(`/api/v1/knowledge/files?spaceId=${kbSpace.data.id}&deleted=true`,{auth:wfEmp.token});
assert.equal(kbTrashFiles.data.records.length,1,'Deleted file lands in recycle bin');
await call(`/api/v1/knowledge/files/${kbFile.data.id}/restore`,{auth:wfEmp.token,method:'POST',body:{}});
await call(`/api/v1/knowledge/documents/${kbDoc.data.id}`,{auth:wfEmp.token,method:'DELETE'});
assert.equal((await call('/api/v1/knowledge/documents/search?keyword='+encodeURIComponent('项目管理'),{auth:wfEmp.token})).data.records.length,0,'Trashed documents disappear from search');
const kbRestore=await call(`/api/v1/knowledge/documents/${kbDoc.data.id}/restore`,{auth:wfEmp.token,method:'POST',body:{}});
assert.equal(kbRestore.code,200,kbRestore.msg);
await call(`/api/v1/knowledge/spaces/${kbSpace.data.id}/members/${wfFin.userId}`,{auth:wfHr.token,method:'DELETE'});
await call(`/api/v1/knowledge/documents/${kbDoc.data.id}`,{auth:wfFin.token,status:404});
await call(`/api/v1/knowledge/spaces/${kbSpace.data.id}/members/${wfEmp.userId}`,{auth:wfEmp.token,method:'DELETE',status:403});
// ---- Module 7 (collaboration) contract smoke ----
const m7Stamp=Date.now();
const m7Room=await call('/api/v1/calendar/rooms',{auth:wfHr.token,method:'POST',body:{name:'M7 Room '+m7Stamp,location:'3F',capacity:8,equipment:'投影'}});
assert.equal(m7Room.code,200,m7Room.msg);
await call('/api/v1/calendar/rooms',{auth:wfEmp.token,method:'POST',body:{name:'M7 Forbidden '+m7Stamp},status:403});
const m7Rooms=await call('/api/v1/calendar/rooms?keyword='+encodeURIComponent('M7 Room '+m7Stamp),{auth:wfEmp.token});
assert.ok(m7Rooms.data.records.some(r=>String(r.id)===String(m7Room.data.id)),'Room list open for booking');
const m7Day='2026-12-15';
const m7t=(h)=>`${m7Day}T${String(h).padStart(2,'0')}:00:00+08:00`;
const m7Range=`start=${m7Day}T00:00:00%2B08:00&end=${m7Day}T23:59:59%2B08:00`;
const m7BookBody={title:'M7 Booking '+m7Stamp,startTime:m7t(2),endTime:m7t(3)};
const m7BookKey=wfIdem();
const m7Bk1=await call(`/api/v1/calendar/rooms/${m7Room.data.id}/bookings`,{auth:wfEmp.token,method:'POST',body:m7BookBody,extraHeaders:idem(m7BookKey)});
assert.equal(m7Bk1.code,200,m7Bk1.msg);
const m7BkReplay=await call(`/api/v1/calendar/rooms/${m7Room.data.id}/bookings`,{auth:wfEmp.token,method:'POST',body:m7BookBody,extraHeaders:idem(m7BookKey)});
assert.equal(String(m7BkReplay.data.id),String(m7Bk1.data.id),'Booking replay returns first result');
await call(`/api/v1/calendar/rooms/${m7Room.data.id}/bookings`,{auth:wfEmp.token,method:'POST',body:{...m7BookBody,title:'M7 Other'},extraHeaders:idem(m7BookKey),status:409});
await call(`/api/v1/calendar/rooms/${m7Room.data.id}/bookings`,{auth:wfLeader.token,method:'POST',body:{title:'M7 Overlap',startTime:m7t(2),endTime:m7t(4)},extraHeaders:idem(wfIdem()),status:409});
const m7Bk2=await call(`/api/v1/calendar/rooms/${m7Room.data.id}/bookings`,{auth:wfLeader.token,method:'POST',body:{title:'M7 BackToBack',startTime:m7t(3),endTime:m7t(4)},extraHeaders:idem(wfIdem())});
assert.equal(m7Bk2.code,200,m7Bk2.msg,'Back-to-back booking allowed (left-closed right-open)');
await call(`/api/v1/calendar/bookings/${m7Bk1.data.id}/checkin`,{method:'PUT',auth:wfEmp.token});
await call(`/api/v1/calendar/bookings/${m7Bk1.data.id}/checkin`,{method:'PUT',auth:wfEmp.token,status:409});
await call(`/api/v1/calendar/bookings/${m7Bk2.data.id}/cancel`,{method:'PUT',auth:wfLeader.token});
await call(`/api/v1/calendar/bookings/${m7Bk2.data.id}/cancel`,{method:'PUT',auth:wfLeader.token,status:409});
await call(`/api/v1/calendar/bookings/${m7Bk2.data.id}/cancel`,{method:'PUT',auth:wfEmp.token,status:403});
const m7EventBody={title:'M7 Private '+m7Stamp,description:'collab smoke',eventType:'2',startTime:m7t(5),endTime:m7t(6),visibility:'1',attendeeIds:[String(wfEmp.userId)],roomId:String(m7Room.data.id)};
const m7Event=await call('/api/v1/calendar/events',{auth:wfHr.token,method:'POST',body:m7EventBody});
assert.equal(m7Event.code,200,m7Event.msg);
assert.equal(String(m7Event.data.roomId),String(m7Room.data.id),'Event links meeting room');
const m7EvBookings=await call(`/api/v1/calendar/rooms/${m7Room.data.id}/bookings?${m7Range}`,{auth:wfEmp.token});
assert.ok(m7EvBookings.data.records.some(b=>String(b.eventId)===String(m7Event.data.id)),'Booking mirrors event one-to-one');
const m7Conflict=await call('/api/v1/calendar/events',{auth:wfHr.token,method:'POST',body:{...m7EventBody,title:'M7 Conflict'},status:409});
assert.equal(m7Conflict.code,409,'Overlapping room event rejected');
await call(`/api/v1/calendar/events/${m7Event.data.id}`,{auth:wfFin.token,status:404});
const m7FinList=await call(`/api/v1/calendar/events?${m7Range}`,{auth:wfFin.token});
assert.ok(!m7FinList.data.records.some(e=>String(e.id)===String(m7Event.data.id)),'Private event hidden from others');
const m7EvView=await call(`/api/v1/calendar/events/${m7Event.data.id}`,{auth:wfEmp.token});
assert.equal(m7EvView.data.myResponse,'PENDING','Attendee sees pending invite');
const m7Accept=await call(`/api/v1/calendar/events/${m7Event.data.id}/accept`,{method:'PUT',auth:wfEmp.token});
assert.equal(m7Accept.data.myResponse,'ACCEPTED','Attendee accepts invite');
await call(`/api/v1/calendar/events/${m7Event.data.id}/reject`,{method:'PUT',auth:wfFin.token,status:403});
const m7Upd=await call(`/api/v1/calendar/events/${m7Event.data.id}`,{auth:wfHr.token,method:'PUT',body:{...m7EventBody,lockVersion:m7Event.data.lockVersion,title:'M7 Private v2'}});
assert.equal(m7Upd.code,200,m7Upd.msg);
const m7Stale=await call(`/api/v1/calendar/events/${m7Event.data.id}`,{auth:wfHr.token,method:'PUT',body:{...m7EventBody,lockVersion:m7Event.data.lockVersion,title:'M7 Stale'},status:409});
assert.equal(m7Stale.code,409,'Stale lockVersion conflicts');
await call(`/api/v1/calendar/events/${m7Event.data.id}`,{auth:wfHr.token,method:'DELETE'});
const m7AfterDel=await call(`/api/v1/calendar/rooms/${m7Room.data.id}/bookings?${m7Range}`,{auth:wfEmp.token});
const m7EvBk=m7AfterDel.data.records.find(b=>String(b.eventId)===String(m7Event.data.id));
assert.equal(m7EvBk.status,4,'Deleted event releases booking but keeps history');
const m7TaskBody={title:'M7 Task '+m7Stamp,assigneeId:String(wfEmp.userId),priority:'2',dueDate:'2026-12-20',memberIds:[String(wfFin.userId)]};
const m7Task=await call('/api/v1/tasks',{auth:wfHr.token,method:'POST',body:m7TaskBody});
assert.equal(m7Task.code,200,m7Task.msg);
assert.equal(m7Task.data.status,1,'New task starts in TODO');
await call(`/api/v1/tasks/${m7Task.data.id}`,{auth:wfLeader.token,status:404});
const m7Prog=await call(`/api/v1/tasks/${m7Task.data.id}/progress`,{auth:wfEmp.token,method:'PUT',body:{lockVersion:m7Task.data.lockVersion,progress:50}});
assert.equal(m7Prog.data.progress,50,'Progress recorded');
const m7St=await call(`/api/v1/tasks/${m7Task.data.id}/status`,{auth:wfEmp.token,method:'PUT',body:{lockVersion:m7Prog.data.lockVersion,status:'2'}});
assert.equal(m7St.data.status,2,'TODO -> IN_PROGRESS');
const m7Done=await call(`/api/v1/tasks/${m7Task.data.id}/status`,{auth:wfEmp.token,method:'PUT',body:{lockVersion:m7St.data.lockVersion,status:'4'}});
assert.equal(m7Done.data.status,4,'IN_PROGRESS -> DONE');
assert.equal(m7Done.data.progress,100,'Done task gets full progress');
const m7Illegal=await call(`/api/v1/tasks/${m7Task.data.id}/status`,{auth:wfEmp.token,method:'PUT',body:{lockVersion:m7Done.data.lockVersion,status:'1'},status:409});
assert.equal(m7Illegal.code,409,'Terminal task rejects status jumps');
await call(`/api/v1/tasks/${m7Task.data.id}`,{auth:wfHr.token,method:'PUT',body:{...m7TaskBody,lockVersion:m7Done.data.lockVersion,title:'M7 Locked'},status:409});
const m7Task2=await call('/api/v1/tasks',{auth:wfHr.token,method:'POST',body:{title:'M7 Task2 '+m7Stamp,assigneeId:String(wfEmp.userId),priority:'3'}});
assert.equal(m7Task2.code,200,m7Task2.msg);
const m7Cmt=await call(`/api/v1/tasks/${m7Task2.data.id}/comments`,{auth:wfHr.token,method:'POST',body:{content:'M7 smoke comment'}});
assert.equal(m7Cmt.data.activityType,4,'Comment recorded as activity');
await call(`/api/v1/tasks/${m7Task2.data.id}/members?userId=${wfLeader.userId}`,{auth:wfHr.token,method:'POST',body:{}});
await call(`/api/v1/tasks/${m7Task2.data.id}/members?userId=${wfLeader.userId}`,{auth:wfHr.token,method:'POST',body:{}});
let m7MemberMsgs=[];
for(let n=0;n<90;n++) {
  const msgs=await call('/api/v1/messages?type=NOTICE&pageSize=100',{auth:wfLeader.token});
  m7MemberMsgs=(msgs.data.records||[]).filter(m=>m.title==='任务协作：'+m7Task2.data.title);
  if(m7MemberMsgs.length>=1) break;
  await new Promise(r=>setTimeout(r,1000));
}
assert.equal(m7MemberMsgs.length,1,'Duplicate member add does not duplicate notification');
const m7Acts=await call(`/api/v1/tasks/${m7Task2.data.id}/activities`,{auth:wfEmp.token});
assert.ok(m7Acts.data.some(a=>a.activityType===4),'Activities include comment');
const m7Board=await call('/api/v1/tasks/board',{auth:wfHr.token});
assert.equal(m7Board.data.columns.length,5,'Board has five status columns');
await call(`/api/v1/tasks/${m7Task2.data.id}`,{auth:wfHr.token,method:'DELETE'});
await call(`/api/v1/tasks/${m7Task2.data.id}`,{auth:wfHr.token,status:404});
// ---- Module 10 (AI M1+M2) contract smoke ----
token=admin;
const m10Stamp=Date.now();
const m10Providers=await call('/api/v1/ai/providers');
assert.ok(Array.isArray(m10Providers.data.records),'渠道分页契约');
const m10Provider=await call('/api/v1/ai/providers',{method:'POST',body:{name:'SMOKE AI '+m10Stamp,providerType:'custom',baseUrl:'http://127.0.0.1:9/v1',apiKey:'sk-smoke-abcdef123456',priority:50,enabled:1}});
assert.equal(m10Provider.code,200,m10Provider.msg);
const m10ProviderId=m10Provider.data.id;
assert.equal(m10Provider.data.apiKeyHint,'sk-***3456','Key 只回显脱敏 hint');
assert.equal('apiKey' in m10Provider.data,false,'明文 Key 不得回显');
assert.equal('apiKeyCipher' in m10Provider.data,false,'密文不得回显');
const m10Probe=await call(`/api/v1/ai/providers/${m10ProviderId}/test`,{method:'POST',body:{modelKey:'smoke-model'}});
assert.equal(m10Probe.data.ok,false,'不可达上游必须判失败');
assert.ok(['UPSTREAM_ERROR','TIMEOUT','AUTH_FAILED','BALANCE','MODEL_NOT_FOUND'].includes(m10Probe.data.errorCategory),'错误分类归一化');
assert.equal(JSON.stringify(m10Probe).includes('sk-smoke-abcdef'),false,'测试连接不得泄露 Key');
const m10Model=await call('/api/v1/ai/models',{method:'POST',body:{providerId:m10ProviderId,modelKey:'smoke-model',capability:['chat'],contextWindow:4096,defaultTemperature:0.7,maxTokens:256,enabled:1,isDefault:0}});
assert.equal(m10Model.code,200,m10Model.msg);
const m10ModelId=m10Model.data.id;
const m10Default=await call('/api/v1/ai/models',{method:'POST',body:{providerId:m10ProviderId,modelKey:'smoke-vision',capability:['chat','vision'],contextWindow:4096,maxTokens:256,enabled:1,isDefault:1}});
assert.equal(m10Default.code,200,m10Default.msg);
await call(`/api/v1/ai/providers/${m10ProviderId}`,{method:'DELETE',status:409});
const m10EnabledModels=await call('/api/v1/ai/models/enabled');
assert.ok(m10EnabledModels.data.length>=2,'启用模型选择器登录即可');
await call('/api/v1/ai/models/enabled',{auth:'',status:401});
const m10User='smoke_ai_'+m10Stamp;
const m10Role=await call('/system/role',{method:'POST',body:{roleName:m10User,roleKey:m10User,roleSort:9,dataScope:'5',status:'0',menuCheckStrictly:true,deptCheckStrictly:true,menuIds:[],deptIds:[]}});
assert.equal(m10Role.code,200,m10Role.msg);
const m10RoleId=(await call('/system/role/list?roleName='+m10User)).rows[0].roleId;
const m10Account=await makeUser('ai',[m10RoleId]); token=m10Account.token;
await call('/api/v1/ai/providers',{status:403});
await call('/api/v1/ai/models',{status:403});
await call('/api/v1/ai/usage/logs',{status:403});
await call('/api/v1/ai/quotas',{status:403});
await call('/api/v1/ai/chat/conversations',{status:403});
await call('/api/v1/ai/chat/templates',{status:200});
await call('/api/v1/ai/kb',{status:403});
await call('/api/v1/ai/qa/history',{status:403});
token=admin;
await call(`/system/user/${m10Account.userId}`,{method:'DELETE'});
await call(`/system/role/${m10RoleId}`,{method:'DELETE'});
token=admin;
const m10BadAttachment=await call('/api/v1/ai/chat/completions',{method:'POST',body:{modelId:m10Default.data.id,content:'图',attachmentIds:['999999']},status:404});
assert.ok(String(m10BadAttachment.msg).includes('AI_ATTACHMENT_NOT_FOUND'),'附件越权/不存在 404');
const pngForm=new FormData();
pngForm.append('file',new Blob([new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,13])],{type:'image/png'}),'smoke.png');
const m10Image=await call('/api/v1/ai/chat/attachments',{method:'POST',body:pngForm});
assert.equal(typeof m10Image.data.fileId,'string','图片附件登记');
const m10Cap=await call('/api/v1/ai/chat/completions',{method:'POST',body:{modelId:m10ModelId,content:'这是什么',attachmentIds:[m10Image.data.fileId]},status:400});
assert.ok(String(m10Cap.msg).includes('MODEL_CAPABILITY_MISMATCH'),'非 vision 模型拒图');
const m10Sse=await fetch(base+'/api/v1/ai/chat/completions',{method:'POST',headers:{clientid:client,Authorization:`Bearer ${admin}`,'Content-Type':'application/json'},body:JSON.stringify({modelId:m10Default.data.id,content:'smoke 流式'})});
checks++;
assert.equal(m10Sse.status,200,'SSE 流式响应 200');
assert.ok(String(m10Sse.headers.get('content-type')).includes('text/event-stream'),'SSE content-type');
const m10SseText=await m10Sse.text();
assert.ok(/event:\s*meta/.test(m10SseText),'SSE 首事件 meta（会话/消息 ID）');
assert.ok(/event:\s*error/.test(m10SseText),'上游不可达时 SSE error 事件');
assert.ok(m10SseText.includes('LLM_UPSTREAM_ERROR'),'错误码归一化');
const m10Quota=await call('/api/v1/ai/quotas',{method:'POST',body:{scopeType:'user',scopeId:session.user.userId,scopeName:'smoke admin',periodType:'day',tokenLimit:1,requestLimit:1,enabled:1}});
assert.equal(m10Quota.code,200,m10Quota.msg);
const m10QuotaHit=await call('/api/v1/ai/chat/completions',{method:'POST',body:{modelId:m10Default.data.id,content:'超限'},status:429});
assert.ok(String(m10QuotaHit.msg).includes('AI_QUOTA_EXCEEDED'),'限额拦截 429');
await call(`/api/v1/ai/quotas/${m10Quota.data.id}`,{method:'DELETE'});
const m10TemplateList=await call('/api/v1/ai/chat/templates');
assert.equal(m10TemplateList.data.length,5,'内置提示词模板五件套');
const m10Templates=await call('/api/v1/ai/prompt-templates');
assert.ok(m10Templates.data.records.some(t=>t.code==='official_doc'),'公文写作模板内置');
const m10Usage=await call('/api/v1/ai/usage/logs');
assert.ok(Array.isArray(m10Usage.data.records),'用量日志分页契约');
const m10Stats=await call('/api/v1/ai/usage/stats');
assert.ok(typeof m10Stats.data.requests==='number','用量统计聚合');
const m10Conv=await call('/api/v1/ai/chat/conversations',{method:'POST',body:{title:'SMOKE 会话'}});
assert.equal(m10Conv.code,200,m10Conv.msg);
await call(`/api/v1/ai/chat/conversations/999999/messages`,{status:404});
const m10ConvList=await call('/api/v1/ai/chat/conversations');
assert.ok(m10ConvList.data.records.some(c=>String(c.id)===String(m10Conv.data.id)),'会话列表包含新会话');
await call(`/api/v1/ai/chat/conversations/${m10Conv.data.id}`,{method:'DELETE'});
await call(`/api/v1/ai/chat/conversations/${m10Conv.data.id}`, {status:404});
const m10QuotaList=await call('/api/v1/ai/quotas');
assert.ok(Array.isArray(m10QuotaList.data.records),'配额分页契约');
// ---- Module 10 (AI M3 knowledge QA) contract smoke ----
const m3Embed=await call('/api/v1/ai/models',{method:'POST',body:{providerId:m10ProviderId,modelKey:'smoke-embed',capability:['embedding'],contextWindow:4096,maxTokens:64,enabled:1,isDefault:0}});
assert.equal(m3Embed.code,200,m3Embed.msg);
const m3Kb=await call('/api/v1/ai/kb',{method:'POST',body:{name:'SMOKE KB '+m10Stamp,visibility:'all',embeddingModelId:m3Embed.data.id,status:'active'}});
assert.equal(m3Kb.code,200,m3Kb.msg);
const m3KbId=m3Kb.data.id;
const m3KbList=await call('/api/v1/ai/kb');
assert.ok(m3KbList.data.records.some(k=>String(k.id)===String(m3KbId)),'知识域列表契约');
const m3Detail=await call(`/api/v1/ai/kb/${m3KbId}`);
assert.equal(m3Detail.data.visibility,'all','知识域详情契约');
const m3NoEmbed=await call('/api/v1/ai/kb',{method:'POST',body:{name:'SMOKE KB-NOEMB '+m10Stamp,visibility:'private',status:'active'}});
assert.equal(m3NoEmbed.code,200,m3NoEmbed.msg);
const m3NoEmbedSource=await call(`/api/v1/ai/kb/${m3NoEmbed.data.id}/sources`,{method:'POST',body:{sourceType:'document',docId:'999999'},status:400});
assert.equal(m3NoEmbedSource.code,400,'embedding 模型未配置登记时拦截');
assert.ok(String(m3NoEmbedSource.msg).includes('EMBEDDING_MODEL_UNAVAILABLE'),'向量模型缺失错误码归一化');
const m3MissingDoc=await call(`/api/v1/ai/kb/${m3KbId}/sources`,{method:'POST',body:{sourceType:'document',docId:'999999'},status:404});
assert.equal(m3MissingDoc.code,404,'不存在/越权文档来源 404');
const m3Chunks=await call(`/api/v1/ai/kb/${m3KbId}/chunks`);
assert.ok(Array.isArray(m3Chunks.data.records),'分块预览契约');
const m3Members=await call(`/api/v1/ai/kb/${m3KbId}/members`,{method:'POST',body:{userIds:[String(m10Account.userId)]}});
assert.equal(m3Members.code,200,m3Members.msg);
const m3MemberList=await call(`/api/v1/ai/kb/${m3KbId}/members`);
assert.ok(m3MemberList.data.length>=1,'知识域成员契约');
await call(`/api/v1/ai/kb/${m3KbId}/members/${m10Account.userId}`,{method:'DELETE'});
const m3Search=await call(`/api/v1/ai/kb/${m3KbId}/search-test`,{method:'POST',body:{query:'smoke'},status:502});
assert.ok(String(m3Search.msg).includes('LLM_UPSTREAM_ERROR'),'检索测试上游错误归一化');
const m3Ask=await call('/api/v1/ai/qa/ask',{method:'POST',body:{kbIds:[String(m3KbId)],query:'smoke'},status:502});
assert.ok(String(m3Ask.msg).includes('LLM_UPSTREAM_ERROR'),'问答检索上游错误归一化');
const m3History=await call('/api/v1/ai/qa/history');
assert.ok(Array.isArray(m3History.data.records),'问答历史契约');
// ---- Module 10 (AI M4 business copilot) contract smoke ----
const m4Scenes=await call('/api/v1/ai/copilot/scenes');
assert.equal(m4Scenes.data.length,5,'copilot scene bootstrap');
assert.ok(m4Scenes.data.some(s=>s.code==='approve-summary'),'copilot scene list');
const m4Off=await call('/api/v1/ai/copilot/scenes/notice-draft',{method:'PUT',body:{enabled:0}});
assert.equal(m4Off.data.enabled,0,'copilot scene disable');
const m4Disabled=await call('/api/v1/ai/copilot/notice-draft',{method:'POST',body:{content:'smoke points'},status:403});
assert.ok(String(m4Disabled.msg).includes('AI_COPILOT_DISABLED'),'disabled scene 403');
await call('/api/v1/ai/copilot/scenes/notice-draft',{method:'PUT',body:{enabled:1}});
const m4Empty=await call('/api/v1/ai/copilot/minutes',{method:'POST',body:{},status:400});
assert.ok(String(m4Empty.msg).includes('AI_COPILOT_INPUT_EMPTY'),'empty input 400');
const m4Unknown=await call('/api/v1/ai/copilot/nope',{method:'POST',body:{content:'x'},status:400});
assert.ok(String(m4Unknown.msg).includes('AI_COPILOT_SCENE_UNKNOWN'),'unknown scene 400');
const m4Sse=await fetch(base+'/api/v1/ai/copilot/report-insight',{method:'POST',headers:{clientid:client,Authorization:`Bearer ${admin}`,'Content-Type':'application/json'},body:JSON.stringify({content:'monthly 120k'})});
checks++;
assert.equal(m4Sse.status,200,'copilot SSE 200');
assert.ok(String(m4Sse.headers.get('content-type')).includes('text/event-stream'),'copilot SSE content-type');
const m4SseText=await m4Sse.text();
assert.ok(/event:\s*meta/.test(m4SseText),'copilot SSE meta');
assert.ok(/event:\s*error/.test(m4SseText),'copilot SSE error on upstream failure');
const m4Tasks=await call('/api/v1/ai/copilot/tasks');
assert.ok(Array.isArray(m4Tasks.data.records),'copilot task page');
if(m4Tasks.data.records.length){
  const m4TaskId=m4Tasks.data.records[0].id;
  await call(`/api/v1/ai/copilot/tasks/${m4TaskId}`,{method:'GET'});
  await call(`/api/v1/ai/copilot/tasks/${m4TaskId}/retry`,{method:'POST'});
}
// ---- Module 10 (AI M5 tools & agents) contract smoke ----
const m5Tools=await call('/api/v1/ai/tools');
assert.ok(m5Tools.data.records.some(t=>t.code==='knowledge_search'),'built-in tools seeded');
assert.ok(m5Tools.data.records.some(t=>t.code==='leave_balance'),'leave balance tool seeded');
assert.ok(m5Tools.data.records.some(t=>t.code==='reimburse_progress'),'reimburse progress tool seeded');
assert.ok(m5Tools.data.records.some(t=>t.code==='notice_search'),'notice search tool seeded');
assert.ok(m5Tools.data.records.some(t=>t.writeFlag===1),'write tools flagged');
const m5Tool=await call('/api/v1/ai/tools',{method:'POST',body:{code:'smoke_tool_'+m10Stamp,name:'SMOKE tool',type:'function',description:'smoke',schemaJson:'{"type":"object","properties":{}}',writeFlag:0,enabled:1}});
assert.equal(m5Tool.code,200,m5Tool.msg);
const m5Dup=await call('/api/v1/ai/tools',{method:'POST',body:{code:'smoke_tool_'+m10Stamp,name:'dup',type:'function'},status:409});
assert.ok(String(m5Dup.msg).includes('AI_TOOL_CODE_EXISTS'),'tool code conflict 409');
const m5Test=await call(`/api/v1/ai/tools/${m5Tool.data.id}/test`,{method:'POST'});
assert.equal(m5Test.data.ok,false,'function tool without impl fails test');
const m5Mcp=await call('/api/v1/ai/tools',{method:'POST',body:{code:'smoke_mcp_'+m10Stamp,name:'SMOKE MCP',type:'mcp',configJson:JSON.stringify({transport:'http',url:'http://127.0.0.1:9/mcp',headers:{Authorization:'Bearer smoke-secret'}}),enabled:1}});
assert.equal(m5Mcp.code,200,m5Mcp.msg);
assert.equal(m5Mcp.data.hasAuthHeader,true,'mcp auth header flagged');
assert.equal(JSON.stringify(m5Mcp).includes('smoke-secret'),false,'mcp auth header never echoed');
const m5Discover=await call(`/api/v1/ai/tools/discover/${m5Mcp.data.id}`,{status:502});
assert.ok(String(m5Discover.msg).includes('AI_MCP_'),'mcp failure normalized');
const m5Import=await call(`/api/v1/ai/tools/discover/${m5Mcp.data.id}/import`,{method:'POST',status:502});
assert.ok(String(m5Import.msg).includes('AI_MCP_'),'mcp import failure normalized');
await call(`/api/v1/ai/tools/${m5Tool.data.id}`,{method:'DELETE'});
await call(`/api/v1/ai/tools/${m5Mcp.data.id}`,{method:'DELETE'});
const m5BuiltinId=m5Tools.data.records.find(t=>t.isBuiltin===1).id;
const m5BuiltinDel=await call(`/api/v1/ai/tools/${m5BuiltinId}`,{method:'DELETE',status:409});
assert.ok(String(m5BuiltinDel.msg).includes('AI_TOOL_BUILTIN_LOCKED'),'built-in tool locked');
const m5Agent=await call('/api/v1/ai/agents',{method:'POST',body:{code:'smoke_agent',name:'SMOKE Agent',systemPrompt:'assistant',toolCodes:['knowledge_search'],maxSteps:3,timeoutSec:30,enabled:1}});
assert.equal(m5Agent.code,200,m5Agent.msg);
const m5RunSse=await fetch(base+`/api/v1/ai/agents/${m5Agent.data.id}/run`,{method:'POST',headers:{clientid:client,Authorization:`Bearer ${admin}`,'Content-Type':'application/json'},body:JSON.stringify({input:'smoke'})});
checks++;
assert.equal(m5RunSse.status,200,'agent run SSE 200');
const m5RunText=await m5RunSse.text();
assert.ok(/event:\s*meta/.test(m5RunText),'agent run SSE meta');
assert.ok(/event:\s*error/.test(m5RunText),'agent run SSE error on upstream failure');
const m5Runs=await call('/api/v1/ai/agents/runs');
assert.ok(m5Runs.data.records.length>=1,'agent run recorded');
const m5Detail=await call(`/api/v1/ai/agents/runs/${m5Runs.data.records[0].id}`);
assert.ok(Array.isArray(m5Detail.data.trace),'agent run trace replayable');
await call(`/api/v1/ai/agents/${m5Agent.data.id}`,{method:'DELETE'});
await call(`/api/v1/ai/kb/${m3KbId}`,{method:'DELETE'});
await call(`/api/v1/ai/kb/${m3NoEmbed.data.id}`,{method:'DELETE'});
await call(`/api/v1/ai/kb/${m3KbId}`,{method:'DELETE',status:404});
await call(`/api/v1/ai/models/${m3Embed.data.id}`,{method:'DELETE'});
await call(`/api/v1/ai/models/${m10ModelId}`,{method:'DELETE'});
await call(`/api/v1/ai/models/${m10Default.data.id}`,{method:'DELETE'});
const m10DelConflict=await call(`/api/v1/ai/providers/${m10ProviderId}`,{method:'DELETE',status:200});
assert.equal(m10DelConflict.code,200,'模型清理后渠道可删除');
token=admin;
await call('/api/v1/auth/logout',{method:'POST'});
await call('/api/v1/auth/profile',{status:401});
writeFileSync(new URL('../.cache/smoke-result.json',import.meta.url),JSON.stringify({time:new Date().toISOString(),checks,result:'PASS'},null,2));
console.log(`PASS: ${checks} HTTP/WebSocket checks; admin password saved locally in deploy/secrets/admin-current-password (not printed).`);
